INSERT INTO PETSTORE.TB_CATEGORIA(CATEGORIA_ID, NOME) VALUES (1, 'CACHORRO');
INSERT INTO PETSTORE.TB_CATEGORIA(CATEGORIA_ID, NOME) VALUES (2, 'GATO');
INSERT INTO PETSTORE.TB_CATEGORIA(CATEGORIA_ID, NOME) VALUES (3, 'AVE');


INSERT INTO PETSTORE.TB_PET (PET_ID, NOME, STATUS, CATEGORIA_ID) VALUES (1,'BOB', 'DISPONIVEL',1);
INSERT INTO PETSTORE.TB_PET (PET_ID, NOME, STATUS, CATEGORIA_ID) VALUES (2,'MONICAO','VENDIDO',1);
INSERT INTO PETSTORE.TB_PET (PET_ID, NOME, STATUS, CATEGORIA_ID) VALUES (3,'THOR','DISPONIVEL',1);
INSERT INTO PETSTORE.TB_PET (PET_ID, NOME, STATUS, CATEGORIA_ID) VALUES (4,'FRED','DISPONIVEL',2);
INSERT INTO PETSTORE.TB_PET (PET_ID, NOME, STATUS, CATEGORIA_ID) VALUES (5,'LISA','VENDIDO',2);

INSERT INTO PETSTORE.TB_COMPRA(COMPRA_ID, PET_ID, QUANTIDADE,DT_COMPRA, STATUS, FINALIZADA) VALUES(1, 5, 1,'2022-8-31','ENTREGUE',true);
INSERT INTO PETSTORE.TB_COMPRA(COMPRA_ID, PET_ID, QUANTIDADE,DT_COMPRA, STATUS, FINALIZADA) VALUES(2, 2, 1,'2022-9-10','ENTREGUE',true);






